### ISSUE TITLE
Broken on Ruby 3

### ISSUE THREAD

**Issue by lserman** [piplcom/piplapis-ruby#15]
`URI.escape` was removed in Ruby 3: https://github.com/ruby/uri/commit/61c6a47ebf1f2726b60a2bbd70964d64e14b1f98

The method is still called from this library.

**Comment by morgan-pipl** [comment]
Thank you for reporting this.  We'll ask the relevant team to take a look.

**Comment by morgan-pipl** [comment]
The development team who owns the client libraries is still working on a fix.  Here's a workaround that can be used for anyone who's blocked by the above until then:

```
# The PIPL library still uses URI.escape (removed in Ruby 3)
URI.extend(Module.new do
  def escape(*args)
    URI::DEFAULT_PARSER.escape(*args)
  end
end)
```
